version: '3.8'
services:
  databank-api:
    image: nmrlipids/databank-api:latest
    pull_policy: always
    ports:
      - "8000:8000"
    environment:
      - DATABANK_PATH=/app/Databank
      - LOCAL_STATIC=/app/static

  portal-backend:
    image: nmrlipids/backend:latest
    pull_policy: always
    ports:
      - "5001:5001"
    env_file:
      - ../startup/backend.env
      - - DATABANK_API_URL=http://databank-api:8000
    depends_on:
      - databank-api
