#First block rerirects HTTP traffic to HTTPS
server {
    listen 80;
    server_name upload-portal.nmrlipids.fi;

    return 301 https://$host$request_uri;
}
# Second block serves React frontend and proxies API request to backend
server {
    listen 443 ssl;
    server_name upload-portal.nmrlipids.fi;
    ssl_certificate     /etc/letsencrypt/live/upload-portal.nmrlipids.fi/fullchain.pem; 
    ssl_certificate_key /etc/letsencrypt/live/upload-portal.nmrlipids.fi/privkey.pem;   
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    # Serve static React build
    root /var/www/frontend/build;
    index index.html;

    #Look for matcching files in build directory, if not found: serve index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Backend routes (Flask)
    location /app/ {
        proxy_pass http://localhost:5001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}

